# Generated by Django 4.1.3 on 2022-11-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='grupo_muscular',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FichaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_treino', models.CharField(choices=[('ABC', 'ACB'), ('AB', 'AB')], max_length=3)),
                ('dias', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.aluno')),
                ('exercicios', models.ManyToManyField(to='plataforma.exercicio')),
            ],
        ),
    ]
