# Generated by Django 4.1.3 on 2022-11-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_exercicio_grupo_muscular_fichatreino'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='grupo_muscular',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='grupo_muscular',
            field=models.ManyToManyField(to='plataforma.grupomuscular'),
        ),
    ]
