# Generated by Django 4.1.3 on 2022-11-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_grupomuscular_remove_exercicio_grupo_muscular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomuscular',
            name='nome',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
