# Generated by Django 4.1.3 on 2022-12-01 11:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_exercicio_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='repeticoes',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='series',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='tecnica',
        ),
        migrations.RemoveField(
            model_name='fichatreino',
            name='exercicios',
        ),
        migrations.AddField(
            model_name='fichatreino',
            name='data_inicio',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('exercicios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.exercicio')),
            ],
        ),
    ]
