# Generated by Django 4.1.3 on 2022-12-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_remove_exercicio_repeticoes_remove_exercicio_series_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='exercicios',
        ),
        migrations.AddField(
            model_name='treino',
            name='exercicios',
            field=models.ManyToManyField(to='plataforma.exercicio'),
        ),
    ]
