# Generated by Django 4.1.3 on 2022-12-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_remove_treino_exercicios_treino_exercicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatreino',
            name='treinos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.treino'),
        ),
    ]
