# Generated by Django 4.1.3 on 2022-12-02 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_fichatreino_treinos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='grupo_muscular',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='exercicios',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='series',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercicio',
            name='tecnica',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fichatreino',
            name='data_inicio',
            field=models.DateField(default=datetime.date(2022, 12, 2)),
        ),
        migrations.CreateModel(
            name='BancoExercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('grupo_muscular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.grupomuscular')),
            ],
        ),
        migrations.AddField(
            model_name='exercicio',
            name='exercio',
            field=models.ManyToManyField(to='plataforma.bancoexercicios'),
        ),
    ]
