# Generated by Django 4.1.3 on 2022-12-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_rename_exercio_exercicio_exercicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FichaTreino',
        ),
    ]
