# Generated by Django 4.1.3 on 2022-12-02 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_treino_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='treino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.treino'),
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='exercicio',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='exercicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.bancoexercicios'),
        ),
    ]
