# Generated by Django 4.1.3 on 2022-12-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_exercicio_treino_remove_exercicio_exercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='treino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.treino'),
        ),
    ]
