# Generated by Django 4.1.3 on 2022-12-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_alter_exercicio_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='exercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.bancoexercicios'),
        ),
    ]
