# Generated by Django 4.1.3 on 2022-12-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_alter_exercicio_exercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='exercicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.bancoexercicios'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='treino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.treino'),
        ),
    ]
