# Generated by Django 4.1.3 on 2022-12-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_alter_exercicio_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
